name: rag
channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip

  - numpy
  - certifi
  - setuptools
  - wheel
  - packaging
  - python-dateutil
  - six
  - tqdm
  - typing_extensions

  - requests
  - urllib3
  - idna
  - charset-normalizer
  - beautifulsoup4
  - soupsieve
  - lxml

  - pyyaml
  - regex
  - zstandard
  - pymysql
  - protobuf

  - gitpython
  - gitdb
  - smmap

  - bleach
  - markdownify
  - webencodings
  - text-unidecode
  - python-slugify

  - pip:
      - turbovec
      - torch==2.10
      - faiss-cpu==1.14.2
      - transformers
      - datasets
      - accelerate
      - sentence-transformers
      - kaggle
      - kagglesdk