name: genshin-rag
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - pip

  - numpy
  - certifi
  - setuptools
  - wheel
  - packaging
  - python-dateutil
  - six
  - tqdm
  - typing_extensions
  - requests
  - urllib3
  - idna
  - charset-normalizer
  - beautifulsoup4
  - soupsieve
  - lxml
  - pyyaml
  - regex
  - zstandard
  - pymysql
  - gitpython
  - gitdb
  - smmap
  - protobuf
  - transformers
  - dataset
  - accelerate
  - peft
  - trl
  - bitsandbytes
  - bleach
  - markdownify
  - webencodings
  - text-unidecode
  - kagglesdk
  - kaggle
  - configparser
  - sentence-transformers
  - python-slugify

  - pip:
      - shutils
      - turbovec