use_default_settings:
  engines:
    remove:
      - ahmia
      - torch
      - wikidata

general:
  debug: false
  instance_name: "Local SearXNG"

search:
  safe_search: 0
  formats:
    - html
    - json

server:
  bind_address: "127.0.0.1"
  port: 8888
  secret_key: "RANDOM_SECRET_KEY"
  limiter: false
  public_instance: false
  image_proxy: false
  method: "GET"

valkey:
  url: false
